language: python
python:
  - "2.7"
  - "3.4"
install:
    - "pip install -r requirements.txt"
    - "pip install coveralls"
script:
    - "coverage run --source=py_wlc setup.py test"
after_success:
    coveralls